/**
 * One-off build helper: download the three brand fonts from Google Fonts as
 * woff2 (latin + latin-ext subsets only — latin-ext carries the ₹ glyph,
 * U+20B9) and emit a self-hosted @font-face stylesheet. Run once; the woff2
 * files and generated CSS are committed so production never touches Google.
 */
import { writeFile, mkdir } from 'node:fs/promises';

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=IBM+Plex+Mono:wght@500;600&family=Work+Sans:wght@400;500;600&display=swap';
const UA =
  'Mozilla/5.0 (Linux; Android 12) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36';
const WANTED = new Set(['latin', 'latin-ext']);

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

await mkdir('public/fonts', { recursive: true });
await mkdir('src/styles', { recursive: true });

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
let cssOut =
  '/*\n * Self-hosted brand fonts — generated by scripts/fetch-fonts.mjs.\n' +
  ' * Subsets: latin + latin-ext (latin-ext provides the Indian Rupee sign,\n' +
  ' * U+20B9). font-display: swap so text paints immediately with a fallback.\n */\n';
const downloads = [];
let m;
while ((m = blockRe.exec(css)) !== null) {
  const subset = m[1];
  if (!WANTED.has(subset)) continue;
  const body = m[2];
  const family = /font-family:\s*'([^']+)'/.exec(body)[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)[1];
  const style = /font-style:\s*(\w+)/.exec(body)[1];
  const unicode = /unicode-range:\s*([^;]+);/.exec(body)[1].trim();
  const url = /url\(([^)]+)\)\s*format\('woff2'\)/.exec(body)[1].replace(/['"]/g, '');
  const slug = family.toLowerCase().replace(/\s+/g, '-');
  const file = `${slug}-${weight}-${subset}.woff2`;
  downloads.push({ url, file });
  cssOut +=
    `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url('/fonts/${file}') format('woff2');unicode-range:${unicode};}\n`;
}

for (const d of downloads) {
  const buf = Buffer.from(await (await fetch(d.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  await writeFile(`public/fonts/${d.file}`, buf);
  console.log('downloaded', d.file, buf.length, 'bytes');
}
await writeFile('src/styles/fonts.css', cssOut);
console.log('wrote src/styles/fonts.css with', downloads.length, 'faces');
