#!/usr/bin/env python3
"""
Regenerate the embedded PDF report fonts (src/report/fonts/reportFonts.ts).

Downloads the full IBM Plex Mono Medium and IBM Plex Serif Bold TTFs, subsets
them to a comprehensive character set, and writes the base64 export module.

Why a *comprehensive* subset (not just "glyphs currently used"): the previous
subset omitted '@', so the header email (info@arthvedawealth.in) truncated to
"info" — jsPDF drops text from the first glyph missing in the embedded font.
The subset below covers all printable ASCII (so '@', '_', etc. are always
present), Latin-1, common punctuation/quotes, the ellipsis used by fitText, and
the currency signs (€, ₹), future-proofing the report against the same bug.

Requires: fonttools, brotli  (pip install fonttools brotli)
Run from the repo root:  python3 scripts/regenerate-report-fonts.py
"""
import base64
import io
import urllib.request

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

BASE = "https://cdn.jsdelivr.net/gh/IBM/plex@v6.4.0"
SOURCES = {
    "REPORT_MONO_FONT_BASE64": f"{BASE}/IBM-Plex-Mono/fonts/complete/ttf/IBMPlexMono-Medium.ttf",
    "REPORT_SERIF_FONT_BASE64": f"{BASE}/IBM-Plex-Serif/fonts/complete/ttf/IBMPlexSerif-Bold.ttf",
}

# Comprehensive, future-proof glyph coverage.
UNICODES = (
    list(range(0x20, 0x7F))   # printable ASCII incl. @ _ and all punctuation
    + list(range(0xA0, 0x100))  # Latin-1 supplement incl. · (U+00B7)
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2122, 0x2212]
    + [0x20AC, 0x20B9]          # € and ₹
)


def subset_to_base64(url: str) -> str:
    raw = urllib.request.urlopen(url, timeout=120).read()  # noqa: S310 (trusted CDN)
    font = TTFont(io.BytesIO(raw))
    options = Options()
    options.layout_features = []   # drop OpenType layout features (unused by jsPDF)
    options.hinting = False        # drop hinting tables (jsPDF does not hint)
    options.name_IDs = ["*"]       # keep name records for a valid TTF
    options.notdef_outline = True
    subsetter = Subsetter(options=options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    out = io.BytesIO()
    font.save(out)
    return base64.b64encode(out.getvalue()).decode("ascii")


def main() -> None:
    parts = [
        "/**",
        " * Embedded report fonts (base64 TTF), subset from IBM Plex Mono Medium",
        " * (values/body) and IBM Plex Serif Bold (headings).",
        " *",
        " * Subset to a comprehensive character set: all printable ASCII (so every",
        " * punctuation mark — including '@' and '_' — always renders), Latin-1, common",
        " * punctuation/quotes, the ellipsis used by fitText, and the € and ₹ currency",
        " * signs. jsPDF drops text from the first glyph missing in an embedded font, so",
        " * a generous subset prevents header/footer truncation (e.g. the contact email).",
        " *",
        " * Generated by scripts/regenerate-report-fonts.py. Do not edit by hand.",
        " */",
        "",
    ]
    for const, url in SOURCES.items():
        b64 = subset_to_base64(url)
        print(f"{const}: {len(b64)} base64 chars")
        parts.append(f"export const {const} =\n  '{b64}';")
        parts.append("")
    open("src/report/fonts/reportFonts.ts", "w").write("\n".join(parts))
    print("wrote src/report/fonts/reportFonts.ts")


if __name__ == "__main__":
    main()
